services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    network_mode: host
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - N8N_HOST=n8n.gurj.ai
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - TZ=UTC
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n


volumes:
  n8n-data:
